BUG FIX: utils::globalVariables() need to be imported.
Currently, reverse package dependency checks report:

```
Error in globalVariables(c(".", ".id", ".rownames", "ci.lower", "ci.upper",  :
  could not find function "globalVariables"
Error: unable to load R code in package ‘broom’
Execution halted
```